### ISSUE TITLE
find out if tag already exists inside of the taglistview?

### ISSUE THREAD

**Issue by viktorwillmann** [ElaWorkshop/TagListView#103]
is there a function to check if a tag already exists so you never add duplicates?

**Comment by aleene** [comment]
No, this more a data management issue, which belongs in the data layer of your app. So you should keep tracks of what tags you add yourself.

**Comment by SomuYadav** [comment]
Hello @viktorwillmann ,
             You can find your answer here, I have added id in TagView, it will solve your problem but make sure you have the unique id for every tag.

[TagListView.zip](https://github.com/ElaWorkshop/TagListView/files/5255500/TagListView.zip)
