### ISSUE TITLE
Strange behavior of TagListView after load

### ISSUE THREAD

**Issue by ruthlessG** [ElaWorkshop/TagListView#107]
Hello!

First of all thanks for your work.

I use TagListView in my current project and it saves a lot of my time.

Short description of an issue:
Neither “tag.onTap” nor “func tagPressed()" work after load and TagListView attributes set in StoryBoard are reset.

Full description of an issue:

I set all the attributes using storyboard as it is advised in readme doc.

I also added TagListViewDelegate to my custom tableView class and implemented “tagListView.delegate = self” in cellForRowAt indexPath. In custom tableViewCell class I have IBOutlet for tagListView as well.

Seems like all is set fine and indeed it works as I think it should. My app adds tags on button click. I also implemented a longPress gestureRecognizer for cell: when the cell is longPressed, the tagListView isUserInterractionEnabled is switched to true and with tag.onTap I can access each tag.

Everything works fine before I close app and run it again.
After this, behavior of loaded tags is strange – attributes set in StoryBoard are ignored – tags are of default gray color, corner radius is set to zero and so on. 
Why do you think this happens?
I temporarily fixed it (seems like not in the best way), I set all this attributes programmatically in cellForRowAt indexPath.

The real problem is that after load neither “tag.onTap” nor “func tagPressed()…”  work. But they both do work perfectly before I close my app and run again. I would appreciate any help on this issue.

PS: I’m quite new to programming and Swift, I use PersistData (described in Apple’s beginner app guide) to save my data, probably I’m supposed to save the attributes of tagListView somehow?!

Thanks in advance one again.

**Comment by uilyd** [comment]
The cells in table view are dynamically loaded. You have to set the attributes of the tag list view programmatically in cellForRowAt indexPath. You should also set delegate in cellForRowAt indexPath.

For this kind of issue, it always good to attach a minimal project that could demo your issue. It’s hard for maintainers to provide useful advices if you only have textual description. Thank you!
