### ISSUE TITLE
Can't use in Interface Builder. 

### ISSUE THREAD

**Issue by MehulSojitra16** [ElaWorkshop/TagListView#122]
Hi,

I am trying to add a TagListView in Interface Builder by assiging a "TagListView" class to UIView but it doesn't allow me to use it.
I am using xcode - 8.3.1 and 1.2.0 version of TagListView.

Here is the issues which i'm facing:
i) Unknown class _TtC6Upmyle11TagListView in Interface Builder file.
![i](https://cloud.githubusercontent.com/assets/16378636/26200676/ee16e784-3bec-11e7-9ba5-1f85174e476b.png)

ii) Unknown class TagListView in Interface Builder file.
![ii](https://cloud.githubusercontent.com/assets/16378636/26200754/4f2a4eda-3bed-11e7-9793-99ebb0aedffc.png)

I have added it using CocoaPods.

**Comment by Cee** [comment]
Try: Module - TagListView

**Comment by MehulSojitra16** [comment]
Now Its working. 
Thank you...
