### ISSUE TITLE
Designable build failed on Xcode 8.3.2 with Swift 3.1

### ISSUE THREAD

**Issue by congnd** [ElaWorkshop/TagListView#123]
Im trying to set class for a view to TagListView, but Xcode tell me that designable build failed.
So i have no way to use interface builder to custom the view. 

I installed TagListView using Carthage.
How can i resolve this problem?

**Comment by Cee** [comment]
#122 #118 may have the same problem. You can try to change the `Module` value to `TagListView`.

**Comment by congnd** [comment]
@Cee 
I have tried to change the `Module` value to  `TagListView`. But Xcode still said that Designable build failed.

Note that i can still use the `TagListView` without the Interface Builder.

**Comment by anti-transmission** [comment]
Fixed by 0e25d9f.
