### ISSUE TITLE
How to add TagListView in textField?

### ISSUE THREAD

**Issue by Bruce9487** [ElaWorkshop/TagListView#125]
Sorry, Im beginner. If I want to add tag in my textField.How to do this?
I have tried on my own.But I also fail to do it.

This is my code: 
https://github.com/Bruce9487/TagViewTest

**Comment by Cee** [comment]
So why you want to display the TagListView in a textfield?

**Comment by xhacker** [comment]
If you want to show tokens like in Mail.app, we don’t support that yet.
