### ISSUE TITLE
Tag list view frame problem for longer text. 

### ISSUE THREAD

**Issue by Samrat555** [ElaWorkshop/TagListView#127]
Tag list view frame problem for longer text. View cut from device screen. Please update the code in TagView.swift file
override open var intrinsicContentSize: CGSize {
        var size = titleLabel?.text?.size(attributes: [NSFontAttributeName: textFont]) ?? CGSize.zero
        size.height = textFont.pointSize + paddingY * 2
        size.width += paddingX * 2
        if size.width < size.height {
            size.width = size.height
        }
        if size.width > UIScreen.main.bounds.width - 40 {
            size.width = UIScreen.main.bounds.width - 40
            self.titleLabel!.numberOfLines = 1
            self.titleLabel!.adjustsFontSizeToFitWidth = true
            self.titleLabel!.lineBreakMode = .byClipping
        }
        if enableRemoveButton {
            size.width += removeButtonIconSize + paddingX
        }
        return size
    }

**Comment by hirenspaceo** [comment]
i added above code in **TagView.swift** file but it is not working. i am using xcode 8.3.2.

**Comment by xhacker** [comment]
We don’t support long tags very well. If you have a solution please make a pull request. Thanks!
