### ISSUE TITLE
Remove Button Doesn't Work

### ISSUE THREAD

**Issue by Flaniga3** [ElaWorkshop/TagListView#130]
I'm having a bit of trouble getting the remove button to work in the iPhone simulator. I've selected the "Enable Remove On" option but when I tap it, it doesn't remove the item. No error is given, there's no stack trace, and there isn't any associated crash.

**Comment by anti-transmission** [comment]
Please try the sample project. It has a `TagListView` with remove button enabled. If that doesn’t help, please attach sample project/code.

**Comment by iOSUser110** [comment]
i am facing same issue

**Comment by jimsmithm3** [comment]
I think I am as well.  

What I am seeing is you can remove the items on the first line only.  If you have several lines the 2nd through end do not seem to pick up the 'x' action.  What's odd is that once something moves up to the first line (something else was removed) it is then able to be removed.  Of note, the selection of the items is also behaving the exact same way for me.

I can reproduce this just by creating a new project.  Adding the library as a pod and then copying the code from the demo project and running it on an attached iPhone SE device.

See https://github.com/jimsmithm3/tag_test3.

**Comment by jimsmithm3** [comment]
This is a constraint issue.  Haven't quite figured it all out yet but somehow your TagListView is resizing to accommodate when multiple lines are added while mine is not.  I guess it's not a bug after all just need to figure out the right combination  of constraints.
