### ISSUE TITLE
Already Selected Tags??

### ISSUE THREAD

**Issue by alexgoodison** [ElaWorkshop/TagListView#135]
I am creating a news app where you can select News Topics using a TagListView. When a tag is selected it adds that topic to an Array in UserDefaults. How can I get it so that when a user comes back to the TagListView, that their selected topics are already selected in the TagListView?

Thanks in advance

**Comment by coderShiv** [comment]
I am facing the same type of issue. How to display preselected tag?

**Comment by alielephant** [comment]
Facing same issue

**Comment by xhacker** [comment]
Thanks @lis186!
