### ISSUE TITLE
Swift 3.1 compile errors

### ISSUE THREAD

**Issue by bassebaba** [ElaWorkshop/TagListView#139]
Hello, I use Swift 3.1 and xcode 8.3.3.
I do a manual install, by downloading from the Swift-3 branch and then dragging the folder into the project.

This gives me a total of 12 compile errors.

Am I doing something wrong, or is the swift3-branch not maintained?

**Comment by anti-transmission** [comment]
It should still work in Swift 3.1. Can you paste the errors here?
