### ISSUE TITLE
Invalid parameter not satisfying: [views count] == 3

### ISSUE THREAD

**Issue by YKV** [ElaWorkshop/TagListView#145]
Hi,
I have a view Controller that structured as shown below:

![screen shot 2017-09-13 at 3 10 21 pm](https://user-images.githubusercontent.com/7923917/30395954-f37b97dc-9895-11e7-9f7b-76bed6dbaa72.png)

As you can see I have container view that holds inside the tabs view controller that's created with CarbonKit. Whenever I tap on tab I call a reusable viewController  which has Collection view.  Whenever I select or deselect collection view cell, the tags view in main view controller gets updated and adding/removing tag view with cell name respectively.

The error "Invalid parameter not satisfying: [views count] == 3"  appears when I switch to previous tab.

Full error:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [views count] == 3'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000117353b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000116db8141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000117357cf2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000011527e3b6 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x00000001140cb8f6 -[_UIQueuingScrollView _replaceViews:updatingContents:adjustContentInsets:animated:] + 279
	5   UIKit                               0x00000001140cf692 -[_UIQueuingScrollView _didScrollWithAnimation:force:] + 1199
	6   UIKit                               0x00000001140cacb9 -[_UIQueuingScrollView _scrollViewAnimationEnded:finished:] + 92
	7   UIKit                               0x0000000113936e73 -[UIAnimator stopAnimation:] + 429
	8   UIKit                               0x0000000113937646 -[UIAnimator(Static) _advanceAnimationsOfType:withTimestamp:] + 282
	9   QuartzCore                          0x0000000112a27767 _ZN2CA7Display15DisplayLinkItem8dispatchEy + 51
	10  QuartzCore                          0x0000000112a2762d _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 439
	11  CoreFoundation                      0x00000001172e6b61 __CFMachPortPerform + 161
	12  CoreFoundation                      0x00000001172e6aa9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	13  CoreFoundation                      0x00000001172e6a21 __CFRunLoopDoSource1 + 465
	14  CoreFoundation                      0x00000001172deba0 __CFRunLoopRun + 2352
	15  CoreFoundation                      0x00000001172de016 CFRunLoopRunSpecific + 406
	16  GraphicsServices                    0x000000011a1e3a24 GSEventRunModal + 62
	17  UIKit                               0x00000001137aa0d4 UIApplicationMain + 159
	18  basil                               0x000000010f7c952f main + 111
	19  libdyld.dylib                       0x00000001185a465d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Thanks!

**Comment by Cee** [comment]
It seems that this problem is not related to TagListView. There should be something wrong with your PageViewController.

Ref: https://stackoverflow.com/questions/19337679/ios-uipageviewcontroller-terminating-app-due-to-uncaught-exception-invalid-pa

**Comment by YKV** [comment]
Thanks, apparently CarbonKit has this issue. Just tried to contact you first since the error disappeared when I removed update function for tagsView.
