### ISSUE TITLE
Lengthly Content not displayed fully.

### ISSUE THREAD

**Issue by anurajl** [ElaWorkshop/TagListView#149]
![screen shot 2017-09-22 at 12 59 44 pm](https://user-images.githubusercontent.com/19928263/30737142-306d5338-9fa3-11e7-9a3a-12d8a13e00f3.png)

When tag content is greater than the width of TagListView, its not fully displayed.
Is there any solution for this issue.?

**Comment by Cee** [comment]
https://developer.apple.com/documentation/uikit/uilabel/1620525-linebreakmode

**Comment by amaurydavid** [comment]
I have the same issue and using 
```
tagView.titleLabel?.lineBreakMode = .byTruncatingTail
tagView.titleLabel?.numberOfLines = 0
```
doesn't help. It seems that the tagView doesn't have any trailing constraint.
