### ISSUE TITLE
Build error in v1.3.0 - incorrect argument in call [have: withAttributes, expected: attributes]

### ISSUE THREAD

**Issue by IchordeDionysos** [ElaWorkshop/TagListView#153]
Is this line still correct?
https://github.com/ElaWorkshop/TagListView/blob/1.3.0/TagListView/TagView.swift#L188

I looked through the versions and realized that this line changed 2 times.

1. Due to the conversion from Swift2 to Swift3 and 
2. From v1.2 to v1.3 

Unfortunately, this last update was a breaking change and the major version number wasn't bumped up so I got real problems with it :/

Xcode Version 9.0 (9A235)
TagListView Version v1.3.0

**Comment by csinghdev** [comment]
I'm also facing the same issue, Please fix this
Xcode Version 9.0 (9A235)
TagListView (1.3.0)
![image](https://user-images.githubusercontent.com/12120756/30898605-cc3c8f0c-a379-11e7-936e-cbe0f938138c.png)

**Comment by Cee** [comment]
It should be correct in Swift 4. So are you guys using Swift 3 in your projects?

Ref: https://developer.apple.com/documentation/foundation/nsstring/1531844-size

**Comment by IchordeDionysos** [comment]
Sure could be correct, I wasn't in to that, but then I would expected incrementing the major version number as it breaks old implementations on (auto)updates and not increasing the minor version number from 1.2 to 1.3 :D.

Because of this cocoapods updated with out my explicit consent I had to declare to only update to 1.2 instead of preventing breaking changes as of a incrementing major version numbers

**Comment by Cee** [comment]
@IchordeDionysos Yes you are right. Version naming of TagListView is now not following semantic versioning guide, as well as we should follow this convention into future dev plan. :)

**Comment by IchordeDionysos** [comment]
Sure could be correct, I wasn't in to that, but then I would expected incrementing the major version number as it breaks old implementations on (auto)updates and not increasing the minor version number from 1.2 to 1.3 :D.

Because of this cocoapods updated with out my explicit consent I had to declare to only update to 1.2 instead of preventing breaking changes as of a incrementing major version numbers
