### ISSUE TITLE
xcode 9.0 issues

### ISSUE THREAD

**Issue by eastswift** [ElaWorkshop/TagListView#156]
var size = titleLabel?.text?.size(withAttributes: [NSAttributedStringKey.font: textFont]) ?? CGSize.zero

I am migrating from swift3 to swift4, but I get error "withAttributes".

**ErrorMessage -> Incorrect argument label in call (have 'withAttributes:', expected 'attributes:')**

**Comment by yjouyang** [comment]
same paoblem

**Comment by Cee** [comment]
<img width="1400" alt="screenshot" src="https://user-images.githubusercontent.com/5436953/32031406-11387e7a-b9cf-11e7-84a4-939f57df3da5.png">

Could you check the `Swift Language Version` in your `Build Settings` section?

**Comment by hammadzz** [comment]
@Cee it is 4.0

This needs to be fixed I have seen the same change made in other libraries for Swift 4.0 Support

**Comment by hammadzz** [comment]
Update your Swift Language Version to Swift 4.0 in .xcproject (as shown above) and then delete .xcworkspace.
Update to pods version 1.3.1 (latest current) as I think I needed to do this for it to work properly
Do pod install
Clean build folder
Build

**Comment by eastswift** [comment]
Thank you. Resolved.
