### ISSUE TITLE
Is there a way to add clear all?

### ISSUE THREAD

**Issue by luai-kalkatawi** [ElaWorkshop/TagListView#163]
Is there a way to add clear all selected item as a function?

Thank you.

**Comment by tarek903** [comment]
add this in TagListView class

```
   open func deSelectAll(){
        
        for tag in self.tagViews {
            tag.isSelected = false
        }
        
    }
```

**Comment by xhacker** [comment]
You can add a category that extends the `TagListView` class and use @tarek903’s method.
