### ISSUE TITLE
tagBorder warning

### ISSUE THREAD

**Issue by Geethanjali14** [ElaWorkshop/TagListView#166]
hi, I keep getting the following error. I tried to use the tagListView inside my view.The error is as follows:
![screen shot 2017-11-20 at 2 55 22 pm](https://user-images.githubusercontent.com/18215847/33011514-37795070-ce04-11e7-9680-81cd2e96562b.png)

**Comment by xhacker** [comment]
Please attach full sample project that can reproduce your issue.
