### ISSUE TITLE
Creating the taglistview programmatically in swift 3 / swift 4

### ISSUE THREAD

**Issue by PLSV** [ElaWorkshop/TagListView#172]
Hi, first of all, love what you guys have done. Really awesome!!

So far, the example and the documentation shows how we can use it using storyboards. Is there also a way to create the taglistview programmatically without using any storyboard? 

It would be great if the plugin can cover this aspect too.

**Comment by Cee** [comment]
Yep. You can use `let tagListView = TagListView()` and then do anything you want.

**Comment by PLSV** [comment]
That's what I first thought of, to use it in the way mentioned above `let tagListView = TagListView()`. But it does not work as it gives me a syntax error. Don't quite remember what it was, but I think it said that there is not such structure as TagListView

**Comment by Cee** [comment]
Have you ever imported this class before using it?

**Comment by PLSV** [comment]
Yes, I did. I definitely imported it. `import TagListView` is the code statement I used to import the said module. 

But it still gives me an error telling me that the module is not there.

**Comment by PLSV** [comment]
It's working now, I guess I did not install the right version of TagListView. I use swift 3, so I had to use the version 1.2.0.
