### ISSUE TITLE
TagList view in scrollable

### ISSUE THREAD

**Issue by Shiju86** [ElaWorkshop/TagListView#178]
If I have too many tags, then how can we use the scrollable view in the same tag list view.

**Comment by PatrickChow** [comment]
just add a TagListView in a scrollView and set constraints.
[how-to-configure-a-uiscrollview-with-auto-layout-in-interface-builder](https://medium.com/@pradeep_chauhan/how-to-configure-a-uiscrollview-with-auto-layout-in-interface-builder-218dcb4022d7) read this article, it will help you to figure out

**Comment by Shiju86** [comment]
![simulator screen shot - iphone 6 - 2018-05-03 at 08 38 54](https://user-images.githubusercontent.com/10924476/39558586-72dd17e4-4ead-11e8-80e0-cfd9fc4b7b09.png)

Thanks for the quick update and your effort. I Appreciate it.
I have attached the screenshot, plz check. Suppose I have too many tags, then tags move out of the screens.

**Comment by PatrickChow** [comment]
Sorry, I can't analyze anything through the screenshot. It seems like you didn't use UIScrollView.
Follow the steps in article which I provided,  TagListView instead of view (which mentioned in  step 9), I tried it before, It works very well. 
But I don't suggest, because it doesn't reuse any view,

**Comment by Shiju86** [comment]
I tried with same. And it works!!

Thanks
