### ISSUE TITLE
tagRemoveButtonPressed stop working suddenly

### ISSUE THREAD

**Issue by shaharukhs** [ElaWorkshop/TagListView#184]
When I click on tag following action is being called

```
func tagPressed(_ title: String, tagView: TagView, sender: TagListView) {
        print("Tag pressed: \(title)")
}
```
but when I click on closeButton 

```
func tagRemoveButtonPressed(_ title: String, tagView: TagView, sender: TagListView) {

}
```

was not being called it was working previously but suddenly stop working.

I am using `Xcode 9.3`

**Comment by Cee** [comment]
Have you tried to update your Xcode to the latest version? And don't forget to set `delegate`.

**Comment by radvansky-tomas** [comment]
Check my pull request, I had same issue with custom TagView

**Comment by kublaios** [comment]
I can confirm that the PR of @radvansky-tomas has helped me get through this.

**Comment by rupesh4545** [comment]
don't forget to set delegate to other TagList also.
