### ISSUE TITLE
Drag into project, then swift compile error

### ISSUE THREAD

**Issue by CACRogerWang** [ElaWorkshop/TagListView#188]
Problem : Swift compiler error in TagView . 

![2018-06-27 6 51 00](https://user-images.githubusercontent.com/26565295/41969824-46efdefa-7a3b-11e8-8400-2312cb741896.png)  

I use cocoaPods in my project, but I need some customize in TagListView.   
So I drag TagListView folder in my project. Then Swift compiler error... ( use Swift 4.1)

**Comment by CACRogerWang** [comment]
I create a folder references, then swift compile pass.

![2018-06-27 8 36 42](https://user-images.githubusercontent.com/26565295/41974217-f05339fc-7a49-11e8-834b-fce10129a2ff.png)

**Comment by Cee** [comment]
What do you mean "Swift Compile Error"? Fails to compile `TagListView`?

**Comment by CACRogerWang** [comment]
I drag TagListView into my project, then build it.  The Errors show up.
  
![2018-06-28 9 50 38](https://user-images.githubusercontent.com/26565295/42008568-cacbeda4-7ab8-11e8-9a18-a2600fc0a634.png)

I guess there are some dependences issue in my project. Because I create a new project, it is work perfect.

**Comment by Cee** [comment]
Could you provide the smallest sample project which would cause this error?

**Comment by CACRogerWang** [comment]
I found the reason. I use **SwifterSwift** in my project.   
**SwifterSwift** is installed by CocoaPods and  is global in my project.   

It's cause overriding non-open var outside of its defining module in TagView.

I can not reproduce the global **SwifterSwift** to show the problem.
I only can import **SwifterSwift** in TagView to reproduce the error.  

[Error_Sample.zip](https://github.com/ElaWorkshop/TagListView/files/2147447/Error_Sample.zip)

**Comment by Cee** [comment]
@CACRogerWang Could you use CocoaPods to manage all of your external packages?

**Comment by aquarhead** [comment]
If you need to customize a package, just fork it and push your changes to your fork.

You can specify git repo in the Podfile, [as documented here](https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo).
