### ISSUE TITLE
update collapse animation for tagListView when add to tableview as Seach tag filter

### ISSUE THREAD

**Issue by fukemy** [ElaWorkshop/TagListView#190]
Hello. I think that would be more effection when apply animation like this: 
https://github.com/Yalantis/SearchFilter/blob/master/gif/dribbble.gif

**Comment by Cee** [comment]
Hmmm, looks pretty fancy to me. Is it possible to create a subclass from `TagListView` and then implement this animation effect within that class?

**Comment by fukemy** [comment]
Hello. i saw that animation like Hero animation but they used in one view, not for transition screen. Can help u much sorry :(

**Comment by fukemy** [comment]
i just done the tag filter animation, then now im stuck in collapse that group view with animation like the above's Gif. Plz help me if you done the animation.
https://vimeo.com/user84971345/review/279684698/dd2c202dcc

**Just uploaded video to vimeo server, may be it will take a white to every can see it**

**Comment by Cee** [comment]
Not so much
