### ISSUE TITLE
Multiple text colour

### ISSUE THREAD

**Issue by naveen114** [ElaWorkshop/TagListView#192]
I have the tags and colour in an array and I set the tag by adding addTag property and the text colour for that tag, but they only pick the text colour of the last element in the array.

**Comment by Cee** [comment]
You can set `textColor` and `selectedTextColor` properties for each tag after adding them to a TagListView.

**Comment by naveen114** [comment]
if let categories = feeds?.categories {
                for i in 0..<categories.count {
                    let dict = categories[i]
                    if let name = dict[WSResponseParams.WS_RESP_PARAM_NAME] as? String {
                        if let colors = dict[WSResponseParams.WS_RESP_PARAM_COLOUR] as? String {
                            homeCell.tagList.addTag(name)
                            homeCell.tagList.textColor = UIColor.init(hex: colors)
                            homeCell.tagList.tag = indexPath.row + i
                        }
                    }
                }
            }

**Comment by naveen114** [comment]
This is my code and it only picks the colour from last index.

**Comment by Cee** [comment]
You should set `tag`'s textColor not `tagList`'s.

**Comment by naveen114** [comment]
tagList is the name of the outlet of TagListView
