### ISSUE TITLE
How can i set only single tag selection at a time?

### ISSUE THREAD

**Issue by hardikamal** [ElaWorkshop/TagListView#205]
Hi,

Is it possible to set only one tag selected at a time?
ie I want the tags to act like radiobutton.

**Comment by defyreborn** [comment]
You can select a single tag with long press.

**Comment by poojakaluskar** [comment]
@hardikamal I don't think it's possible at the moment with the library. I had similar requirements in my code and I ended up deselecting other tags when one tag is being selected. 

   `mytag.onTap = {tapView in
     // unselect other tags
  }`

**Comment by NirajCapermint** [comment]
@poojakaluskar how to achieve that? Please provide example or code.

**Comment by NirajCapermint** [comment]
@hardikamal user this

`func tagPressed(_ title: String, tagView: TagView, sender: TagListView) {
        print("Tag pressed: \(title), \(sender)")
        for ta in sender.tagViews {
            if ta.titleLabel?.text == title {
                ta.isSelected = !ta.isSelected
            }else{
                ta.isSelected = false
            }
        }
    }`
