### ISSUE TITLE
Please increase pod version and release 

### ISSUE THREAD

**Issue by swojtyna** [ElaWorkshop/TagListView#221]
According to changes for Swift 5 you have to bump **s.version = "1.3.2"** to **1.3.3** in **TagListView.podspec** to be visible in cocoapods.

**Comment by Cee** [comment]
@xhacker would help :)

**Comment by pnozykowski** [comment]
I hope it will be fixed soon, this is the last library that blocks us to fully migrate to Swift 5. Maybe you shouldn't hardcode swift version in podspec?

**Comment by csvenja** [comment]
1.4.0 has been released.

**Comment by csvenja** [comment]
1.4.0 has been released.
