### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by Drusy** [ElaWorkshop/TagListView#244]
Since Xcode 11 includes Swift Package Manager, it would be nice to support it

**Comment by zeusent** [comment]
Any news on this? This should be fairly easy to setup

**Comment by smamczak** [comment]
I want to switch to SPM too. Looking at Issues count I am worried that to project is no longer maintained at the moment

**Comment by nithingeorgesonin** [comment]
Any updates on Swift package support

**Comment by zeusent** [comment]
I did do this by myself a couple of weeks back. https://github.com/zeusent/TagListView/commit/749d416331e975d310879100e91d492e53304262

Should I maybe make a PR?
