### ISSUE TITLE
Use library through SPM doesn't work

### ISSUE THREAD

**Issue by mrsnow-git** [ElaWorkshop/TagListView#264]
Hello,

I'm trying to use your lib by SPM, but can't complete it - on last phase it bring me a error:

https://github.com/ElaWorkshop/TagListView has no Package.swift manifest for version 1.4.0

I tried it on two XCode version - one on 12 beta 5 and another one on stable 11 (e708).

Not understand what's happens here, doesn't see the problem on brief look - Package.swift is presented as I see.

**Comment by jlynch1** [comment]
Hi, 

I also encountered the same issue, which seems to be the 1.4 tag is not applied on Package.swift file as can be seen here
https://github.com/ElaWorkshop/TagListView/tree/1.4.0

Jonathan

**Comment by csvenja** [comment]
Fixed in 1.4.1.
