### ISSUE TITLE
Release swift 3 support to Cocoapods

### ISSUE THREAD

**Issue by RonKliffer** [ElaWorkshop/TagListView#70]

**Comment by RonKliffer** [comment]
@xhacker Any ETA when this will be released?

**Comment by xhacker** [comment]
@RonKliffer: I’m going to take a look in a day or two.

**Comment by macbaszii** [comment]
@xhacker I got stuck with that as well, plaese. Thanks in advance.

**Comment by RolandasRazma** [comment]
works for me targeting master

pod "TagListView", :git  => "git@github.com:xhacker/TagListView.git", :branch => "master"

**Comment by xhacker** [comment]
Swift 3 support released as 1.1.0. Please test ;)
