### ISSUE TITLE
more complete delegate

### ISSUE THREAD

**Issue by Alex293** [ElaWorkshop/TagListView#81]
Can't make a clean PR for now but this should be easy to integrate : 
added in TagLisViewDelegate : 
@objc optional func tagListViewDidAdd(sender: TagListView, tagView: TagView) -> Void
@objc optional func tagListViewDidRemove(sender: TagListView, tagView: TagView) -> Void
@objc optional func tagListViewDidRemoveAll(sender: TagListView) -> Void

then at the end of addTagView(tagView: TagView) :  
delegate?.tagListViewDidAdd?(sender : self, tagView: tagView)

then at the end of removeTagView(tagView: TagView) : 
delegate?.tagListViewDidRemove?(sender : self, tagView: tagView)

then at the end of removeAllTags() : 
delegate?.tagListViewDidRemoveAll?(sender : self)

So it now easy to keep track of tags title in the tagListView

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38832919-more-complete-delegate?utm_campaign=plugin&utm_content=tracker%2F16419772&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16419772&utm_medium=issues&utm_source=github).

**Comment by aleene** [comment]
What would you like to use this for?

**Comment by Alex293** [comment]
Keeping tracks of titles. On screen I prefix my tags with a # sometimes but when I want to add them to another tag list view I sometimes need to get the title without the #. Found this o be very convenient.

But it's not limited to this it allow you to react how you want when the list has changed

**Comment by aleene** [comment]
Is it also related to keeping tagViews and data in sync? I was thinking of adding an index of tagView. I need it to sync TagView and data removals.
It seems to me you mix what is displayed and what data you have. Maybe you can use a `willAdd(tag: String) -> String`, where you add the #

**Comment by Alex293** [comment]
Yes it's mostly to keep data and ui in sync but I didn't found a more direct way.

My setup is I have a taglistview containing available tags and a selected taglistview. When I click a tag from the first one it should be added to the second and removed from the first one. Same thing in the other direction. The first one need to have # in front of title but not the second one. And I need to keep track of every thing in strings arrays for backend purposes. With my delegates it's very straight forward but you can drop them if you have a better solution. It's mostly what I needed in my project.

I think the best way to do it is that taglistview should use a object instead of a string implementing a delegate for being presented in a tag view so we could have a showed title and a different content

**Comment by aleene** [comment]
I have a somewhat related problem. The current delegate does not provide me with the index of the tag. If interface and data are in sync, the indices should be the same. My issue is deletion of tags. The current tapDelegate function only gives me the TagView that has been used, but I do not know where it was in the TagListView. And I can not use the tag of the TagView is this is ambiguous.

I would like to have a `tagListView(tagListView: TagListView, didSelectTagAtIndex index: Int)`. Anytime a user taps a tag, this is called, and can be acted upon. This can be useful for deleting and selecting tags.

Would this work for you?

**Comment by Alex293** [comment]
I think to address all those king of issues the best way to go would be to mimic the table view delegate you would then have inserting, deleting, selecting.. And it would be more convenient for people as you could keep your usual way to solve issues.

**Comment by aleene** [comment]
I have created a first attempt of a tableView like approach to TagListView. If you are interested check out my fork and patch 8.
