### ISSUE TITLE
Feature request: possibility to have only unique tags

### ISSUE THREAD

**Issue by sverin** [ElaWorkshop/TagListView#86]
At the moment there is no way to make the list of tags unique. I want a feature that enables the view to only add a tag if it's not in the list allready.

```
taglistView.addTag("electronics (0)");
taglistView.addTag("games (0)");
taglistView.addTag("games (0)");
taglistView.addTag("vehicles (0)");
```
<img width="530" alt="skarmavbild 2016-11-11 kl 21 16 45" src="https://cloud.githubusercontent.com/assets/2380634/20228991/547f31b6-a854-11e6-97ab-c581c1d5ddbc.png">

results in two tags, but I only want one.

<img width="410" alt="skarmavbild 2016-11-11 kl 21 17 28" src="https://cloud.githubusercontent.com/assets/2380634/20228996/595ef0f4-a854-11e6-8da3-4210c399dd20.png">

Perhaps a new settings or as a default behavior.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39160368-feature-request-possibility-to-have-only-unique-tags?utm_campaign=plugin&utm_content=tracker%2F16419772&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16419772&utm_medium=issues&utm_source=github).

**Comment by aquarhead** [comment]
```

**Comment by aquarhead** [comment]
I'm not familiar with Swift, but I think you can (need to) subclass the `TagListView` this way.

The current `addTag` returns a `TagView` not `TagView?`, thus if you don't actually add anything you can't really return anything. So you have to make a new method with an optional return.

You can try this with the demo project, just remember to set the correct class in Storyboard.

If you think this fulfills your need, please close the issue.

**Comment by sverin** [comment]
Yes, of course I can subclass, but I think it would be a great feature for the project.

**Comment by aquarhead** [comment]
Well I don't really think so. If you want things to be unique, you should do it at the persistent/database/model layer (whatever you want to call it) and not really relying on presentation/view layer (again whatever you want to call it).

**Comment by sverin** [comment]
okey, fair enough. I'll subclass
