### ISSUE TITLE
Add multi tags at one time

### ISSUE THREAD

**Issue by tinpont** [ElaWorkshop/TagListView#87]
Can I add multi tags at one time? Something like `addTags` function.

Now I can just add tag one by one, which will slow down performance.
```Objc
- (NSArray<TagView *> *)addTags:(NSArray<NSString *> *)tagNames {
    for (NSString *tagName in tagNames) {
        [self addTag:tagName];
    }
    return self.tagViews;
}
```

**Comment by aleene** [comment]
The advantage is not very big. Either the user does the for-loop, or TagListView does it.

Or am I missing something?

**Comment by tinpont** [comment]
@aleene Now add tag will trigger `rearrangeViews` function. This function will calculate TagListView height(and other operation such as `removeFromSuperview`, `clearArray` etc.) when you add single tag.

Image that if I have a UITableView, which has 10 cells, each cell has 10 tags. Without `addTags`, TagListView will call `rearrangeViews` 10 times each cell, the whole tableView will take 100 times. With `addTags`, just only call `rearrangeViews` 10 times. 10x faster.

**Comment by aleene** [comment]
Try this: 

```
    @discardableResult
    open func addTags(_ titles: [String]) -> [TagView] {
        var tagViews: [TagView] = []
        for title in titles {
            tagViews.append(createNewTagView(title))
        }
        return addTagViews(tagViews)
    }

```

**Comment by tinpont** [comment]
Sure I can modify source or subclass when I import these files directly. But I using Carthage for dependency manage, and my project still using Objective-C, which make me can not subclass swift class. Thats the reason I create this feature request issue.

**Comment by redent** [comment]
This is already implemented in #100

**Comment by tinpont** [comment]
Thanks very much, @aleene @redent . This should be closed.

**Comment by mikeknapp** [comment]
Thanks for adding this!! This is a huge improvement -- I have over 100 tags, and it is very slow to load currently.

One thing that prevents me from adding the new function however is that there is no easy way to disable onlongpress. That functionality makes no sense to me. Currently I can override it as I create each tag individually.

Would it be possible to make this optional? Maybe it's a flag that can be set?

**Comment by yuravake** [comment]
I think in future updates this method  was refactored to use addTagView in loop, witch  rearranges views for each new element. This really hits on performance when you add tags in bulk.

`@discardableResult
    open func addTagView(_ tagView: TagView) -> TagView {
        defer { rearrangeViews() }
        tagViews.append(tagView)
        tagBackgroundViews.append(UIView(frame: tagView.bounds))
        
        return tagView
    }
    
    @discardableResult
    open func addTagViews(_ tagViews: [TagView]) -> [TagView] {
        tagViews.forEach {
            addTagView($0)
        }
        return tagViews
    }`
Can we revert those changes or tweak this behavior? 
Thanks.
