### ISSUE TITLE
Selecting a tag

### ISSUE THREAD

**Issue by mrfarukturgut** [ElaWorkshop/TagListView#91]
Hi. Does the library allow us to select a tag and change its background colour different from each other?

**Comment by aleene** [comment]
This is not sufficient?
```
let tagView = tagListView.addTag("blue")
tagView.tagBackgroundColor = UIColor.blueColor()
```

**Comment by mrfarukturgut** [comment]
I asked this because there is a statement in readme as follows,

> Be aware that if you update a property (e.g. tagBackgroundColor) for a TagListView, all the inner TagViews will be updated.

if the snippet you suggested is gonna change all the tag's background it won't gonna work for me. I am expected to do something like; https://codentrick.com/home/wp-content/uploads/2015/07/Following.png

**Comment by aleene** [comment]
Setup the layout for all tags through TagListView once. Afterwards you can change the layout of individual tagViews. So you should be ok, I use it that way.

**Comment by mrfarukturgut** [comment]
Will I be able to write block which will be executed when I press any tagView?

**Comment by aleene** [comment]
Setup your class as delegate of TagListView and then call:
```
func tagPressed(title: String, tagView: TagView, sender: TagListView) {
    your code here
}
```
Will this work for you?

**Comment by mrfarukturgut** [comment]
Absolutely yes! thank you for your help and patience. Enjoy your 800th star 👍

**Comment by xhacker** [comment]
Thanks @aleene for answering! 👍
